names = [
    "Breadboard",
    "Button",
    "Buzzer",
    "Infared_Sensor",
    "Keypad",
    "LCD",
    "LED",
    "LED_Matrix",
    "Number_LED",
    "Photoresistor",
    "Potentiometer",
    "Remote",
    "Resistor",
    "Rheostat",
    "Servo_Engine",
    "Thermistor",
    "Tool_Box",
    "Tool_Box_Tray",
    "UNO_R3",
    "USB_Cable",
    "Ultrasonic_Sensor",
    "Wire",
]

resize_mapping = {
    "640": [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 16, 17, 18, 19, 20, 21],
    "1536": [6, 12, 14, 15],
}

temp_result = {
    "Breadboard": 0,
    "Button": 0,
    "Buzzer": 0,
    "Infared_Sensor": 0,
    "Keypad": 0,
    "LCD": 0,
    "LED": 0,
    "LED_Matrix": 0,
    "Number_LED": 0,
    "Photoresistor": 0,
    "Potentiometer": 0,
    "Remote": 0,
    "Resistor": 0,
    "Rheostat": 0,
    "Servo_Engine": 0,
    "Thermistor": 0,
    "Tool_Box": 0,
    "Tool_Box_Tray": 0,
    "UNO_R3": 0,
    "USB_Cable": 0,
    "Ultrasonic_Sensor": 0,
    "Wire": 0,
}
